# Makefile.in generated by automake 1.10 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006  Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.




pkgdatadir = $(datadir)/full-package-name
pkglibdir = $(libdir)/full-package-name
pkgincludedir = $(includedir)/full-package-name
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
bin_PROGRAMS = gmo$(EXEEXT) gmodebug$(EXEEXT)
subdir = .
DIST_COMMON = README $(am__configure_deps) $(srcdir)/Makefile.am \
	$(srcdir)/Makefile.in $(top_srcdir)/configure AUTHORS COPYING \
	ChangeLog INSTALL NEWS depcomp install-sh missing \
	mkinstalldirs
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_CLEAN_FILES =
am__installdirs = "$(DESTDIR)$(bindir)"
binPROGRAMS_INSTALL = $(INSTALL_PROGRAM)
PROGRAMS = $(bin_PROGRAMS)
am_gmo_OBJECTS = gmo-compalone.$(OBJEXT) gmo-evolution.$(OBJEXT) \
	gmo-dynamics.$(OBJEXT) gmo-generatelat.$(OBJEXT) \
	gmo-definelat.$(OBJEXT) gmo-lattice.$(OBJEXT) \
	gmo-read.$(OBJEXT) gmo-save.$(OBJEXT) gmo-pngwrite.$(OBJEXT) \
	gmo-locerror.$(OBJEXT) gmo-measurements.$(OBJEXT) \
	gmo-opti.$(OBJEXT) gmo-in_development.$(OBJEXT)
gmo_OBJECTS = $(am_gmo_OBJECTS)
gmo_LDADD = $(LDADD)
am_gmodebug_OBJECTS = gmodebug-compalone.$(OBJEXT) \
	gmodebug-dynamics.$(OBJEXT) gmodebug-evolution.$(OBJEXT) \
	gmodebug-generatelat.$(OBJEXT) gmodebug-definelat.$(OBJEXT) \
	gmodebug-lattice.$(OBJEXT) gmodebug-read.$(OBJEXT) \
	gmodebug-save.$(OBJEXT) gmodebug-pngwrite.$(OBJEXT) \
	gmodebug-locerror.$(OBJEXT) gmodebug-measurements.$(OBJEXT) \
	gmodebug-opti.$(OBJEXT) gmodebug-in_development.$(OBJEXT)
gmodebug_OBJECTS = $(am_gmodebug_OBJECTS)
gmodebug_LDADD = $(LDADD)
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
SOURCES = $(gmo_SOURCES) $(gmodebug_SOURCES)
DIST_SOURCES = $(gmo_SOURCES) $(gmodebug_SOURCES)
ETAGS = etags
CTAGS = ctags
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  { test ! -d $(distdir) \
    || { find $(distdir) -type d ! -perm -200 -exec chmod u+w {} ';' \
         && rm -fr $(distdir); }; }
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
distuninstallcheck_listfiles = find . -type f -print
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /Users/kevin/cellmech_sims/heart_project/missing --run aclocal-1.10
AMTAR = ${SHELL} /Users/kevin/cellmech_sims/heart_project/missing --run tar
AUTOCONF = ${SHELL} /Users/kevin/cellmech_sims/heart_project/missing --run autoconf
AUTOHEADER = ${SHELL} /Users/kevin/cellmech_sims/heart_project/missing --run autoheader
AUTOMAKE = ${SHELL} /Users/kevin/cellmech_sims/heart_project/missing --run automake-1.10
AWK = gawk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
CPP = gcc -E
CPPFLAGS = 
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
ECHO_C = \c
ECHO_N = 
ECHO_T = 
EGREP = /usr/bin/grep -E
EXEEXT = 
GREP = /usr/bin/grep
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LDFLAGS = 
LIBOBJS = 
LIBS = -lm 
LTLIBOBJS = 
MAKEINFO = ${SHELL} /Users/kevin/cellmech_sims/heart_project/missing --run makeinfo
MKDIR_P = ./install-sh -c -d
OBJEXT = o
PACKAGE = full-package-name
PACKAGE_BUGREPORT = BUG-REPORT-ADDRESS
PACKAGE_NAME = FULL-PACKAGE-NAME
PACKAGE_STRING = FULL-PACKAGE-NAME VERSION
PACKAGE_TARNAME = full-package-name
PACKAGE_VERSION = VERSION
PATH_SEPARATOR = :
SET_MAKE = 
SHELL = /bin/sh
STRIP = 
VERSION = VERSION
abs_builddir = /Users/kevin/cellmech_sims/heart_project
abs_srcdir = /Users/kevin/cellmech_sims/heart_project
abs_top_builddir = /Users/kevin/cellmech_sims/heart_project
abs_top_srcdir = /Users/kevin/cellmech_sims/heart_project
ac_ct_CC = gcc
am__include = include
am__leading_dot = .
am__quote = 
am__tar = ${AMTAR} chof - "$$tardir"
am__untar = ${AMTAR} xf -
bindir = ${exec_prefix}/bin
build_alias = 
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host_alias = 
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = $(SHELL) /Users/kevin/cellmech_sims/heart_project/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(top_builddir)/./install-sh -c -d
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_builddir = .
top_srcdir = .
gmo_SOURCES = compalone.c compalone.h evolution.c evolution.h dynamics.c dynamics.h generatelat.c generatelat.h definelat.c definelat.h lattice.c lattice.h read.c read.h save.c save.h pngwrite.c pngwrite.h locerror.c locerror.h measurements.c measurements.h opti.c opti.h in_development.c in_development.h const.h
gmo_CPPFLAGS = -O2
gmodebug_SOURCES = compalone.c compalone.h dynamics.c dynamics.h evolution.c evolution.h generatelat.c generatelat.h definelat.c definelat.h lattice.c lattice.h read.c read.h save.c save.h pngwrite.c pngwrite.h locerror.c locerror.h measurements.c measurements.h opti.c opti.h in_development.c in_development.h const.h
gmodebug_CPPFLAGS = -ggdb -O2 
all: all-am

.SUFFIXES:
.SUFFIXES: .c .o .obj
am--refresh:
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --gnu '; \
	      cd $(srcdir) && $(AUTOMAKE) --gnu  \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --gnu  Makefile'; \
	cd $(top_srcdir) && \
	  $(AUTOMAKE) --gnu  Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	cd $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	cd $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	test -z "$(bindir)" || $(MKDIR_P) "$(DESTDIR)$(bindir)"
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  p1=`echo $$p|sed 's/$(EXEEXT)$$//'`; \
	  if test -f $$p \
	  ; then \
	    f=`echo "$$p1" | sed 's,^.*/,,;$(transform);s/$$/$(EXEEXT)/'`; \
	   echo " $(INSTALL_PROGRAM_ENV) $(binPROGRAMS_INSTALL) '$$p' '$(DESTDIR)$(bindir)/$$f'"; \
	   $(INSTALL_PROGRAM_ENV) $(binPROGRAMS_INSTALL) "$$p" "$(DESTDIR)$(bindir)/$$f" || exit 1; \
	  else :; fi; \
	done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  f=`echo "$$p" | sed 's,^.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/'`; \
	  echo " rm -f '$(DESTDIR)$(bindir)/$$f'"; \
	  rm -f "$(DESTDIR)$(bindir)/$$f"; \
	done

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)
gmo$(EXEEXT): $(gmo_OBJECTS) $(gmo_DEPENDENCIES) 
	@rm -f gmo$(EXEEXT)
	$(LINK) $(gmo_OBJECTS) $(gmo_LDADD) $(LIBS)
gmodebug$(EXEEXT): $(gmodebug_OBJECTS) $(gmodebug_DEPENDENCIES) 
	@rm -f gmodebug$(EXEEXT)
	$(LINK) $(gmodebug_OBJECTS) $(gmodebug_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/gmo-compalone.Po
include ./$(DEPDIR)/gmo-definelat.Po
include ./$(DEPDIR)/gmo-dynamics.Po
include ./$(DEPDIR)/gmo-evolution.Po
include ./$(DEPDIR)/gmo-generatelat.Po
include ./$(DEPDIR)/gmo-in_development.Po
include ./$(DEPDIR)/gmo-lattice.Po
include ./$(DEPDIR)/gmo-locerror.Po
include ./$(DEPDIR)/gmo-measurements.Po
include ./$(DEPDIR)/gmo-opti.Po
include ./$(DEPDIR)/gmo-pngwrite.Po
include ./$(DEPDIR)/gmo-read.Po
include ./$(DEPDIR)/gmo-save.Po
include ./$(DEPDIR)/gmodebug-compalone.Po
include ./$(DEPDIR)/gmodebug-definelat.Po
include ./$(DEPDIR)/gmodebug-dynamics.Po
include ./$(DEPDIR)/gmodebug-evolution.Po
include ./$(DEPDIR)/gmodebug-generatelat.Po
include ./$(DEPDIR)/gmodebug-in_development.Po
include ./$(DEPDIR)/gmodebug-lattice.Po
include ./$(DEPDIR)/gmodebug-locerror.Po
include ./$(DEPDIR)/gmodebug-measurements.Po
include ./$(DEPDIR)/gmodebug-opti.Po
include ./$(DEPDIR)/gmodebug-pngwrite.Po
include ./$(DEPDIR)/gmodebug-read.Po
include ./$(DEPDIR)/gmodebug-save.Po

.c.o:
	$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	mv -f $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c $<

.c.obj:
	$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	mv -f $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c `$(CYGPATH_W) '$<'`

gmo-compalone.o: compalone.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmo_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT gmo-compalone.o -MD -MP -MF $(DEPDIR)/gmo-compalone.Tpo -c -o gmo-compalone.o `test -f 'compalone.c' || echo '$(srcdir)/'`compalone.c
	mv -f $(DEPDIR)/gmo-compalone.Tpo $(DEPDIR)/gmo-compalone.Po
#	source='compalone.c' object='gmo-compalone.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmo_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o gmo-compalone.o `test -f 'compalone.c' || echo '$(srcdir)/'`compalone.c

gmo-compalone.obj: compalone.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmo_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT gmo-compalone.obj -MD -MP -MF $(DEPDIR)/gmo-compalone.Tpo -c -o gmo-compalone.obj `if test -f 'compalone.c'; then $(CYGPATH_W) 'compalone.c'; else $(CYGPATH_W) '$(srcdir)/compalone.c'; fi`
	mv -f $(DEPDIR)/gmo-compalone.Tpo $(DEPDIR)/gmo-compalone.Po
#	source='compalone.c' object='gmo-compalone.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmo_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o gmo-compalone.obj `if test -f 'compalone.c'; then $(CYGPATH_W) 'compalone.c'; else $(CYGPATH_W) '$(srcdir)/compalone.c'; fi`

gmo-evolution.o: evolution.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmo_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT gmo-evolution.o -MD -MP -MF $(DEPDIR)/gmo-evolution.Tpo -c -o gmo-evolution.o `test -f 'evolution.c' || echo '$(srcdir)/'`evolution.c
	mv -f $(DEPDIR)/gmo-evolution.Tpo $(DEPDIR)/gmo-evolution.Po
#	source='evolution.c' object='gmo-evolution.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmo_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o gmo-evolution.o `test -f 'evolution.c' || echo '$(srcdir)/'`evolution.c

gmo-evolution.obj: evolution.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmo_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT gmo-evolution.obj -MD -MP -MF $(DEPDIR)/gmo-evolution.Tpo -c -o gmo-evolution.obj `if test -f 'evolution.c'; then $(CYGPATH_W) 'evolution.c'; else $(CYGPATH_W) '$(srcdir)/evolution.c'; fi`
	mv -f $(DEPDIR)/gmo-evolution.Tpo $(DEPDIR)/gmo-evolution.Po
#	source='evolution.c' object='gmo-evolution.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmo_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o gmo-evolution.obj `if test -f 'evolution.c'; then $(CYGPATH_W) 'evolution.c'; else $(CYGPATH_W) '$(srcdir)/evolution.c'; fi`

gmo-dynamics.o: dynamics.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmo_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT gmo-dynamics.o -MD -MP -MF $(DEPDIR)/gmo-dynamics.Tpo -c -o gmo-dynamics.o `test -f 'dynamics.c' || echo '$(srcdir)/'`dynamics.c
	mv -f $(DEPDIR)/gmo-dynamics.Tpo $(DEPDIR)/gmo-dynamics.Po
#	source='dynamics.c' object='gmo-dynamics.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmo_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o gmo-dynamics.o `test -f 'dynamics.c' || echo '$(srcdir)/'`dynamics.c

gmo-dynamics.obj: dynamics.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmo_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT gmo-dynamics.obj -MD -MP -MF $(DEPDIR)/gmo-dynamics.Tpo -c -o gmo-dynamics.obj `if test -f 'dynamics.c'; then $(CYGPATH_W) 'dynamics.c'; else $(CYGPATH_W) '$(srcdir)/dynamics.c'; fi`
	mv -f $(DEPDIR)/gmo-dynamics.Tpo $(DEPDIR)/gmo-dynamics.Po
#	source='dynamics.c' object='gmo-dynamics.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmo_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o gmo-dynamics.obj `if test -f 'dynamics.c'; then $(CYGPATH_W) 'dynamics.c'; else $(CYGPATH_W) '$(srcdir)/dynamics.c'; fi`

gmo-generatelat.o: generatelat.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmo_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT gmo-generatelat.o -MD -MP -MF $(DEPDIR)/gmo-generatelat.Tpo -c -o gmo-generatelat.o `test -f 'generatelat.c' || echo '$(srcdir)/'`generatelat.c
	mv -f $(DEPDIR)/gmo-generatelat.Tpo $(DEPDIR)/gmo-generatelat.Po
#	source='generatelat.c' object='gmo-generatelat.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmo_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o gmo-generatelat.o `test -f 'generatelat.c' || echo '$(srcdir)/'`generatelat.c

gmo-generatelat.obj: generatelat.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmo_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT gmo-generatelat.obj -MD -MP -MF $(DEPDIR)/gmo-generatelat.Tpo -c -o gmo-generatelat.obj `if test -f 'generatelat.c'; then $(CYGPATH_W) 'generatelat.c'; else $(CYGPATH_W) '$(srcdir)/generatelat.c'; fi`
	mv -f $(DEPDIR)/gmo-generatelat.Tpo $(DEPDIR)/gmo-generatelat.Po
#	source='generatelat.c' object='gmo-generatelat.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmo_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o gmo-generatelat.obj `if test -f 'generatelat.c'; then $(CYGPATH_W) 'generatelat.c'; else $(CYGPATH_W) '$(srcdir)/generatelat.c'; fi`

gmo-definelat.o: definelat.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmo_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT gmo-definelat.o -MD -MP -MF $(DEPDIR)/gmo-definelat.Tpo -c -o gmo-definelat.o `test -f 'definelat.c' || echo '$(srcdir)/'`definelat.c
	mv -f $(DEPDIR)/gmo-definelat.Tpo $(DEPDIR)/gmo-definelat.Po
#	source='definelat.c' object='gmo-definelat.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmo_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o gmo-definelat.o `test -f 'definelat.c' || echo '$(srcdir)/'`definelat.c

gmo-definelat.obj: definelat.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmo_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT gmo-definelat.obj -MD -MP -MF $(DEPDIR)/gmo-definelat.Tpo -c -o gmo-definelat.obj `if test -f 'definelat.c'; then $(CYGPATH_W) 'definelat.c'; else $(CYGPATH_W) '$(srcdir)/definelat.c'; fi`
	mv -f $(DEPDIR)/gmo-definelat.Tpo $(DEPDIR)/gmo-definelat.Po
#	source='definelat.c' object='gmo-definelat.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmo_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o gmo-definelat.obj `if test -f 'definelat.c'; then $(CYGPATH_W) 'definelat.c'; else $(CYGPATH_W) '$(srcdir)/definelat.c'; fi`

gmo-lattice.o: lattice.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmo_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT gmo-lattice.o -MD -MP -MF $(DEPDIR)/gmo-lattice.Tpo -c -o gmo-lattice.o `test -f 'lattice.c' || echo '$(srcdir)/'`lattice.c
	mv -f $(DEPDIR)/gmo-lattice.Tpo $(DEPDIR)/gmo-lattice.Po
#	source='lattice.c' object='gmo-lattice.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmo_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o gmo-lattice.o `test -f 'lattice.c' || echo '$(srcdir)/'`lattice.c

gmo-lattice.obj: lattice.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmo_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT gmo-lattice.obj -MD -MP -MF $(DEPDIR)/gmo-lattice.Tpo -c -o gmo-lattice.obj `if test -f 'lattice.c'; then $(CYGPATH_W) 'lattice.c'; else $(CYGPATH_W) '$(srcdir)/lattice.c'; fi`
	mv -f $(DEPDIR)/gmo-lattice.Tpo $(DEPDIR)/gmo-lattice.Po
#	source='lattice.c' object='gmo-lattice.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmo_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o gmo-lattice.obj `if test -f 'lattice.c'; then $(CYGPATH_W) 'lattice.c'; else $(CYGPATH_W) '$(srcdir)/lattice.c'; fi`

gmo-read.o: read.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmo_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT gmo-read.o -MD -MP -MF $(DEPDIR)/gmo-read.Tpo -c -o gmo-read.o `test -f 'read.c' || echo '$(srcdir)/'`read.c
	mv -f $(DEPDIR)/gmo-read.Tpo $(DEPDIR)/gmo-read.Po
#	source='read.c' object='gmo-read.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmo_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o gmo-read.o `test -f 'read.c' || echo '$(srcdir)/'`read.c

gmo-read.obj: read.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmo_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT gmo-read.obj -MD -MP -MF $(DEPDIR)/gmo-read.Tpo -c -o gmo-read.obj `if test -f 'read.c'; then $(CYGPATH_W) 'read.c'; else $(CYGPATH_W) '$(srcdir)/read.c'; fi`
	mv -f $(DEPDIR)/gmo-read.Tpo $(DEPDIR)/gmo-read.Po
#	source='read.c' object='gmo-read.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmo_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o gmo-read.obj `if test -f 'read.c'; then $(CYGPATH_W) 'read.c'; else $(CYGPATH_W) '$(srcdir)/read.c'; fi`

gmo-save.o: save.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmo_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT gmo-save.o -MD -MP -MF $(DEPDIR)/gmo-save.Tpo -c -o gmo-save.o `test -f 'save.c' || echo '$(srcdir)/'`save.c
	mv -f $(DEPDIR)/gmo-save.Tpo $(DEPDIR)/gmo-save.Po
#	source='save.c' object='gmo-save.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmo_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o gmo-save.o `test -f 'save.c' || echo '$(srcdir)/'`save.c

gmo-save.obj: save.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmo_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT gmo-save.obj -MD -MP -MF $(DEPDIR)/gmo-save.Tpo -c -o gmo-save.obj `if test -f 'save.c'; then $(CYGPATH_W) 'save.c'; else $(CYGPATH_W) '$(srcdir)/save.c'; fi`
	mv -f $(DEPDIR)/gmo-save.Tpo $(DEPDIR)/gmo-save.Po
#	source='save.c' object='gmo-save.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmo_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o gmo-save.obj `if test -f 'save.c'; then $(CYGPATH_W) 'save.c'; else $(CYGPATH_W) '$(srcdir)/save.c'; fi`

gmo-pngwrite.o: pngwrite.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmo_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT gmo-pngwrite.o -MD -MP -MF $(DEPDIR)/gmo-pngwrite.Tpo -c -o gmo-pngwrite.o `test -f 'pngwrite.c' || echo '$(srcdir)/'`pngwrite.c
	mv -f $(DEPDIR)/gmo-pngwrite.Tpo $(DEPDIR)/gmo-pngwrite.Po
#	source='pngwrite.c' object='gmo-pngwrite.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmo_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o gmo-pngwrite.o `test -f 'pngwrite.c' || echo '$(srcdir)/'`pngwrite.c

gmo-pngwrite.obj: pngwrite.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmo_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT gmo-pngwrite.obj -MD -MP -MF $(DEPDIR)/gmo-pngwrite.Tpo -c -o gmo-pngwrite.obj `if test -f 'pngwrite.c'; then $(CYGPATH_W) 'pngwrite.c'; else $(CYGPATH_W) '$(srcdir)/pngwrite.c'; fi`
	mv -f $(DEPDIR)/gmo-pngwrite.Tpo $(DEPDIR)/gmo-pngwrite.Po
#	source='pngwrite.c' object='gmo-pngwrite.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmo_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o gmo-pngwrite.obj `if test -f 'pngwrite.c'; then $(CYGPATH_W) 'pngwrite.c'; else $(CYGPATH_W) '$(srcdir)/pngwrite.c'; fi`

gmo-locerror.o: locerror.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmo_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT gmo-locerror.o -MD -MP -MF $(DEPDIR)/gmo-locerror.Tpo -c -o gmo-locerror.o `test -f 'locerror.c' || echo '$(srcdir)/'`locerror.c
	mv -f $(DEPDIR)/gmo-locerror.Tpo $(DEPDIR)/gmo-locerror.Po
#	source='locerror.c' object='gmo-locerror.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmo_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o gmo-locerror.o `test -f 'locerror.c' || echo '$(srcdir)/'`locerror.c

gmo-locerror.obj: locerror.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmo_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT gmo-locerror.obj -MD -MP -MF $(DEPDIR)/gmo-locerror.Tpo -c -o gmo-locerror.obj `if test -f 'locerror.c'; then $(CYGPATH_W) 'locerror.c'; else $(CYGPATH_W) '$(srcdir)/locerror.c'; fi`
	mv -f $(DEPDIR)/gmo-locerror.Tpo $(DEPDIR)/gmo-locerror.Po
#	source='locerror.c' object='gmo-locerror.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmo_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o gmo-locerror.obj `if test -f 'locerror.c'; then $(CYGPATH_W) 'locerror.c'; else $(CYGPATH_W) '$(srcdir)/locerror.c'; fi`

gmo-measurements.o: measurements.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmo_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT gmo-measurements.o -MD -MP -MF $(DEPDIR)/gmo-measurements.Tpo -c -o gmo-measurements.o `test -f 'measurements.c' || echo '$(srcdir)/'`measurements.c
	mv -f $(DEPDIR)/gmo-measurements.Tpo $(DEPDIR)/gmo-measurements.Po
#	source='measurements.c' object='gmo-measurements.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmo_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o gmo-measurements.o `test -f 'measurements.c' || echo '$(srcdir)/'`measurements.c

gmo-measurements.obj: measurements.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmo_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT gmo-measurements.obj -MD -MP -MF $(DEPDIR)/gmo-measurements.Tpo -c -o gmo-measurements.obj `if test -f 'measurements.c'; then $(CYGPATH_W) 'measurements.c'; else $(CYGPATH_W) '$(srcdir)/measurements.c'; fi`
	mv -f $(DEPDIR)/gmo-measurements.Tpo $(DEPDIR)/gmo-measurements.Po
#	source='measurements.c' object='gmo-measurements.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmo_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o gmo-measurements.obj `if test -f 'measurements.c'; then $(CYGPATH_W) 'measurements.c'; else $(CYGPATH_W) '$(srcdir)/measurements.c'; fi`

gmo-opti.o: opti.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmo_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT gmo-opti.o -MD -MP -MF $(DEPDIR)/gmo-opti.Tpo -c -o gmo-opti.o `test -f 'opti.c' || echo '$(srcdir)/'`opti.c
	mv -f $(DEPDIR)/gmo-opti.Tpo $(DEPDIR)/gmo-opti.Po
#	source='opti.c' object='gmo-opti.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmo_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o gmo-opti.o `test -f 'opti.c' || echo '$(srcdir)/'`opti.c

gmo-opti.obj: opti.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmo_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT gmo-opti.obj -MD -MP -MF $(DEPDIR)/gmo-opti.Tpo -c -o gmo-opti.obj `if test -f 'opti.c'; then $(CYGPATH_W) 'opti.c'; else $(CYGPATH_W) '$(srcdir)/opti.c'; fi`
	mv -f $(DEPDIR)/gmo-opti.Tpo $(DEPDIR)/gmo-opti.Po
#	source='opti.c' object='gmo-opti.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmo_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o gmo-opti.obj `if test -f 'opti.c'; then $(CYGPATH_W) 'opti.c'; else $(CYGPATH_W) '$(srcdir)/opti.c'; fi`

gmo-in_development.o: in_development.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmo_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT gmo-in_development.o -MD -MP -MF $(DEPDIR)/gmo-in_development.Tpo -c -o gmo-kevin_tools.o `test -f 'kevin_tools.c' || echo '$(srcdir)/'`kevin_tools.c
	mv -f $(DEPDIR)/gmo-in_development.Tpo $(DEPDIR)/gmo-in_development.Po
#	source='in_development.c' object='gmo-in_development.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmo_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o gmo-in_development.o `test -f 'in_development.c' || echo '$(srcdir)/'`kevin_tools.c

gmo-in_development.obj: in_development.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmo_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT gmo-in_development.obj -MD -MP -MF $(DEPDIR)/gmo-in_development.Tpo -c -o gmo-kevin_tools.obj `if test -f 'kevin_tools.c'; then $(CYGPATH_W) 'kevin_tools.c'; else $(CYGPATH_W) '$(srcdir)/kevin_tools.c'; fi`
	mv -f $(DEPDIR)/gmo-in_development.Tpo $(DEPDIR)/gmo-in_development.Po
#	source='in_development.c' object='gmo-in_development.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmo_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o gmo-in_development.obj `if test -f 'in_development.c'; then $(CYGPATH_W) 'kevin_tools.c'; else $(CYGPATH_W) '$(srcdir)/kevin_tools.c'; fi`

gmodebug-compalone.o: compalone.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmodebug_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT gmodebug-compalone.o -MD -MP -MF $(DEPDIR)/gmodebug-compalone.Tpo -c -o gmodebug-compalone.o `test -f 'compalone.c' || echo '$(srcdir)/'`compalone.c
	mv -f $(DEPDIR)/gmodebug-compalone.Tpo $(DEPDIR)/gmodebug-compalone.Po
#	source='compalone.c' object='gmodebug-compalone.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmodebug_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o gmodebug-compalone.o `test -f 'compalone.c' || echo '$(srcdir)/'`compalone.c

gmodebug-compalone.obj: compalone.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmodebug_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT gmodebug-compalone.obj -MD -MP -MF $(DEPDIR)/gmodebug-compalone.Tpo -c -o gmodebug-compalone.obj `if test -f 'compalone.c'; then $(CYGPATH_W) 'compalone.c'; else $(CYGPATH_W) '$(srcdir)/compalone.c'; fi`
	mv -f $(DEPDIR)/gmodebug-compalone.Tpo $(DEPDIR)/gmodebug-compalone.Po
#	source='compalone.c' object='gmodebug-compalone.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmodebug_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o gmodebug-compalone.obj `if test -f 'compalone.c'; then $(CYGPATH_W) 'compalone.c'; else $(CYGPATH_W) '$(srcdir)/compalone.c'; fi`

gmodebug-dynamics.o: dynamics.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmodebug_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT gmodebug-dynamics.o -MD -MP -MF $(DEPDIR)/gmodebug-dynamics.Tpo -c -o gmodebug-dynamics.o `test -f 'dynamics.c' || echo '$(srcdir)/'`dynamics.c
	mv -f $(DEPDIR)/gmodebug-dynamics.Tpo $(DEPDIR)/gmodebug-dynamics.Po
#	source='dynamics.c' object='gmodebug-dynamics.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmodebug_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o gmodebug-dynamics.o `test -f 'dynamics.c' || echo '$(srcdir)/'`dynamics.c

gmodebug-dynamics.obj: dynamics.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmodebug_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT gmodebug-dynamics.obj -MD -MP -MF $(DEPDIR)/gmodebug-dynamics.Tpo -c -o gmodebug-dynamics.obj `if test -f 'dynamics.c'; then $(CYGPATH_W) 'dynamics.c'; else $(CYGPATH_W) '$(srcdir)/dynamics.c'; fi`
	mv -f $(DEPDIR)/gmodebug-dynamics.Tpo $(DEPDIR)/gmodebug-dynamics.Po
#	source='dynamics.c' object='gmodebug-dynamics.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmodebug_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o gmodebug-dynamics.obj `if test -f 'dynamics.c'; then $(CYGPATH_W) 'dynamics.c'; else $(CYGPATH_W) '$(srcdir)/dynamics.c'; fi`

gmodebug-evolution.o: evolution.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmodebug_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT gmodebug-evolution.o -MD -MP -MF $(DEPDIR)/gmodebug-evolution.Tpo -c -o gmodebug-evolution.o `test -f 'evolution.c' || echo '$(srcdir)/'`evolution.c
	mv -f $(DEPDIR)/gmodebug-evolution.Tpo $(DEPDIR)/gmodebug-evolution.Po
#	source='evolution.c' object='gmodebug-evolution.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmodebug_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o gmodebug-evolution.o `test -f 'evolution.c' || echo '$(srcdir)/'`evolution.c

gmodebug-evolution.obj: evolution.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmodebug_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT gmodebug-evolution.obj -MD -MP -MF $(DEPDIR)/gmodebug-evolution.Tpo -c -o gmodebug-evolution.obj `if test -f 'evolution.c'; then $(CYGPATH_W) 'evolution.c'; else $(CYGPATH_W) '$(srcdir)/evolution.c'; fi`
	mv -f $(DEPDIR)/gmodebug-evolution.Tpo $(DEPDIR)/gmodebug-evolution.Po
#	source='evolution.c' object='gmodebug-evolution.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmodebug_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o gmodebug-evolution.obj `if test -f 'evolution.c'; then $(CYGPATH_W) 'evolution.c'; else $(CYGPATH_W) '$(srcdir)/evolution.c'; fi`

gmodebug-generatelat.o: generatelat.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmodebug_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT gmodebug-generatelat.o -MD -MP -MF $(DEPDIR)/gmodebug-generatelat.Tpo -c -o gmodebug-generatelat.o `test -f 'generatelat.c' || echo '$(srcdir)/'`generatelat.c
	mv -f $(DEPDIR)/gmodebug-generatelat.Tpo $(DEPDIR)/gmodebug-generatelat.Po
#	source='generatelat.c' object='gmodebug-generatelat.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmodebug_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o gmodebug-generatelat.o `test -f 'generatelat.c' || echo '$(srcdir)/'`generatelat.c

gmodebug-generatelat.obj: generatelat.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmodebug_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT gmodebug-generatelat.obj -MD -MP -MF $(DEPDIR)/gmodebug-generatelat.Tpo -c -o gmodebug-generatelat.obj `if test -f 'generatelat.c'; then $(CYGPATH_W) 'generatelat.c'; else $(CYGPATH_W) '$(srcdir)/generatelat.c'; fi`
	mv -f $(DEPDIR)/gmodebug-generatelat.Tpo $(DEPDIR)/gmodebug-generatelat.Po
#	source='generatelat.c' object='gmodebug-generatelat.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmodebug_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o gmodebug-generatelat.obj `if test -f 'generatelat.c'; then $(CYGPATH_W) 'generatelat.c'; else $(CYGPATH_W) '$(srcdir)/generatelat.c'; fi`

gmodebug-definelat.o: definelat.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmodebug_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT gmodebug-definelat.o -MD -MP -MF $(DEPDIR)/gmodebug-definelat.Tpo -c -o gmodebug-definelat.o `test -f 'definelat.c' || echo '$(srcdir)/'`definelat.c
	mv -f $(DEPDIR)/gmodebug-definelat.Tpo $(DEPDIR)/gmodebug-definelat.Po
#	source='definelat.c' object='gmodebug-definelat.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmodebug_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o gmodebug-definelat.o `test -f 'definelat.c' || echo '$(srcdir)/'`definelat.c

gmodebug-definelat.obj: definelat.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmodebug_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT gmodebug-definelat.obj -MD -MP -MF $(DEPDIR)/gmodebug-definelat.Tpo -c -o gmodebug-definelat.obj `if test -f 'definelat.c'; then $(CYGPATH_W) 'definelat.c'; else $(CYGPATH_W) '$(srcdir)/definelat.c'; fi`
	mv -f $(DEPDIR)/gmodebug-definelat.Tpo $(DEPDIR)/gmodebug-definelat.Po
#	source='definelat.c' object='gmodebug-definelat.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmodebug_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o gmodebug-definelat.obj `if test -f 'definelat.c'; then $(CYGPATH_W) 'definelat.c'; else $(CYGPATH_W) '$(srcdir)/definelat.c'; fi`

gmodebug-lattice.o: lattice.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmodebug_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT gmodebug-lattice.o -MD -MP -MF $(DEPDIR)/gmodebug-lattice.Tpo -c -o gmodebug-lattice.o `test -f 'lattice.c' || echo '$(srcdir)/'`lattice.c
	mv -f $(DEPDIR)/gmodebug-lattice.Tpo $(DEPDIR)/gmodebug-lattice.Po
#	source='lattice.c' object='gmodebug-lattice.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmodebug_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o gmodebug-lattice.o `test -f 'lattice.c' || echo '$(srcdir)/'`lattice.c

gmodebug-lattice.obj: lattice.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmodebug_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT gmodebug-lattice.obj -MD -MP -MF $(DEPDIR)/gmodebug-lattice.Tpo -c -o gmodebug-lattice.obj `if test -f 'lattice.c'; then $(CYGPATH_W) 'lattice.c'; else $(CYGPATH_W) '$(srcdir)/lattice.c'; fi`
	mv -f $(DEPDIR)/gmodebug-lattice.Tpo $(DEPDIR)/gmodebug-lattice.Po
#	source='lattice.c' object='gmodebug-lattice.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmodebug_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o gmodebug-lattice.obj `if test -f 'lattice.c'; then $(CYGPATH_W) 'lattice.c'; else $(CYGPATH_W) '$(srcdir)/lattice.c'; fi`

gmodebug-read.o: read.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmodebug_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT gmodebug-read.o -MD -MP -MF $(DEPDIR)/gmodebug-read.Tpo -c -o gmodebug-read.o `test -f 'read.c' || echo '$(srcdir)/'`read.c
	mv -f $(DEPDIR)/gmodebug-read.Tpo $(DEPDIR)/gmodebug-read.Po
#	source='read.c' object='gmodebug-read.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmodebug_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o gmodebug-read.o `test -f 'read.c' || echo '$(srcdir)/'`read.c

gmodebug-read.obj: read.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmodebug_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT gmodebug-read.obj -MD -MP -MF $(DEPDIR)/gmodebug-read.Tpo -c -o gmodebug-read.obj `if test -f 'read.c'; then $(CYGPATH_W) 'read.c'; else $(CYGPATH_W) '$(srcdir)/read.c'; fi`
	mv -f $(DEPDIR)/gmodebug-read.Tpo $(DEPDIR)/gmodebug-read.Po
#	source='read.c' object='gmodebug-read.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmodebug_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o gmodebug-read.obj `if test -f 'read.c'; then $(CYGPATH_W) 'read.c'; else $(CYGPATH_W) '$(srcdir)/read.c'; fi`

gmodebug-save.o: save.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmodebug_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT gmodebug-save.o -MD -MP -MF $(DEPDIR)/gmodebug-save.Tpo -c -o gmodebug-save.o `test -f 'save.c' || echo '$(srcdir)/'`save.c
	mv -f $(DEPDIR)/gmodebug-save.Tpo $(DEPDIR)/gmodebug-save.Po
#	source='save.c' object='gmodebug-save.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmodebug_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o gmodebug-save.o `test -f 'save.c' || echo '$(srcdir)/'`save.c

gmodebug-save.obj: save.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmodebug_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT gmodebug-save.obj -MD -MP -MF $(DEPDIR)/gmodebug-save.Tpo -c -o gmodebug-save.obj `if test -f 'save.c'; then $(CYGPATH_W) 'save.c'; else $(CYGPATH_W) '$(srcdir)/save.c'; fi`
	mv -f $(DEPDIR)/gmodebug-save.Tpo $(DEPDIR)/gmodebug-save.Po
#	source='save.c' object='gmodebug-save.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmodebug_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o gmodebug-save.obj `if test -f 'save.c'; then $(CYGPATH_W) 'save.c'; else $(CYGPATH_W) '$(srcdir)/save.c'; fi`

gmodebug-pngwrite.o: pngwrite.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmodebug_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT gmodebug-pngwrite.o -MD -MP -MF $(DEPDIR)/gmodebug-pngwrite.Tpo -c -o gmodebug-pngwrite.o `test -f 'pngwrite.c' || echo '$(srcdir)/'`pngwrite.c
	mv -f $(DEPDIR)/gmodebug-pngwrite.Tpo $(DEPDIR)/gmodebug-pngwrite.Po
#	source='pngwrite.c' object='gmodebug-pngwrite.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmodebug_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o gmodebug-pngwrite.o `test -f 'pngwrite.c' || echo '$(srcdir)/'`pngwrite.c

gmodebug-pngwrite.obj: pngwrite.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmodebug_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT gmodebug-pngwrite.obj -MD -MP -MF $(DEPDIR)/gmodebug-pngwrite.Tpo -c -o gmodebug-pngwrite.obj `if test -f 'pngwrite.c'; then $(CYGPATH_W) 'pngwrite.c'; else $(CYGPATH_W) '$(srcdir)/pngwrite.c'; fi`
	mv -f $(DEPDIR)/gmodebug-pngwrite.Tpo $(DEPDIR)/gmodebug-pngwrite.Po
#	source='pngwrite.c' object='gmodebug-pngwrite.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmodebug_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o gmodebug-pngwrite.obj `if test -f 'pngwrite.c'; then $(CYGPATH_W) 'pngwrite.c'; else $(CYGPATH_W) '$(srcdir)/pngwrite.c'; fi`

gmodebug-locerror.o: locerror.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmodebug_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT gmodebug-locerror.o -MD -MP -MF $(DEPDIR)/gmodebug-locerror.Tpo -c -o gmodebug-locerror.o `test -f 'locerror.c' || echo '$(srcdir)/'`locerror.c
	mv -f $(DEPDIR)/gmodebug-locerror.Tpo $(DEPDIR)/gmodebug-locerror.Po
#	source='locerror.c' object='gmodebug-locerror.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmodebug_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o gmodebug-locerror.o `test -f 'locerror.c' || echo '$(srcdir)/'`locerror.c

gmodebug-locerror.obj: locerror.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmodebug_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT gmodebug-locerror.obj -MD -MP -MF $(DEPDIR)/gmodebug-locerror.Tpo -c -o gmodebug-locerror.obj `if test -f 'locerror.c'; then $(CYGPATH_W) 'locerror.c'; else $(CYGPATH_W) '$(srcdir)/locerror.c'; fi`
	mv -f $(DEPDIR)/gmodebug-locerror.Tpo $(DEPDIR)/gmodebug-locerror.Po
#	source='locerror.c' object='gmodebug-locerror.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmodebug_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o gmodebug-locerror.obj `if test -f 'locerror.c'; then $(CYGPATH_W) 'locerror.c'; else $(CYGPATH_W) '$(srcdir)/locerror.c'; fi`

gmodebug-measurements.o: measurements.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmodebug_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT gmodebug-measurements.o -MD -MP -MF $(DEPDIR)/gmodebug-measurements.Tpo -c -o gmodebug-measurements.o `test -f 'measurements.c' || echo '$(srcdir)/'`measurements.c
	mv -f $(DEPDIR)/gmodebug-measurements.Tpo $(DEPDIR)/gmodebug-measurements.Po
#	source='measurements.c' object='gmodebug-measurements.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmodebug_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o gmodebug-measurements.o `test -f 'measurements.c' || echo '$(srcdir)/'`measurements.c

gmodebug-measurements.obj: measurements.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmodebug_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT gmodebug-measurements.obj -MD -MP -MF $(DEPDIR)/gmodebug-measurements.Tpo -c -o gmodebug-measurements.obj `if test -f 'measurements.c'; then $(CYGPATH_W) 'measurements.c'; else $(CYGPATH_W) '$(srcdir)/measurements.c'; fi`
	mv -f $(DEPDIR)/gmodebug-measurements.Tpo $(DEPDIR)/gmodebug-measurements.Po
#	source='measurements.c' object='gmodebug-measurements.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmodebug_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o gmodebug-measurements.obj `if test -f 'measurements.c'; then $(CYGPATH_W) 'measurements.c'; else $(CYGPATH_W) '$(srcdir)/measurements.c'; fi`

gmodebug-opti.o: opti.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmodebug_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT gmodebug-opti.o -MD -MP -MF $(DEPDIR)/gmodebug-opti.Tpo -c -o gmodebug-opti.o `test -f 'opti.c' || echo '$(srcdir)/'`opti.c
	mv -f $(DEPDIR)/gmodebug-opti.Tpo $(DEPDIR)/gmodebug-opti.Po
#	source='opti.c' object='gmodebug-opti.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmodebug_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o gmodebug-opti.o `test -f 'opti.c' || echo '$(srcdir)/'`opti.c

gmodebug-opti.obj: opti.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmodebug_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT gmodebug-opti.obj -MD -MP -MF $(DEPDIR)/gmodebug-opti.Tpo -c -o gmodebug-opti.obj `if test -f 'opti.c'; then $(CYGPATH_W) 'opti.c'; else $(CYGPATH_W) '$(srcdir)/opti.c'; fi`
	mv -f $(DEPDIR)/gmodebug-opti.Tpo $(DEPDIR)/gmodebug-opti.Po
#	source='opti.c' object='gmodebug-opti.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmodebug_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o gmodebug-opti.obj `if test -f 'opti.c'; then $(CYGPATH_W) 'opti.c'; else $(CYGPATH_W) '$(srcdir)/opti.c'; fi`

gmodebug-in_development.o: in_development.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmodebug_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT gmodebug-in_development.o -MD -MP -MF $(DEPDIR)/gmodebug-in_development.Tpo -c -o gmodebug-kevin_tools.o `test -f 'kevin_tools.c' || echo '$(srcdir)/'`kevin_tools.c
	mv -f $(DEPDIR)/gmodebug-in_development.Tpo $(DEPDIR)/gmodebug-in_development.Po
#	source='in_development.c' object='gmodebug-in_development.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmodebug_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o gmodebug-in_development.o `test -f 'in_development.c' || echo '$(srcdir)/'`kevin_tools.c

gmodebug-in_development.obj: in_development.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmodebug_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT gmodebug-in_development.obj -MD -MP -MF $(DEPDIR)/gmodebug-in_development.Tpo -c -o gmodebug-kevin_tools.obj `if test -f 'kevin_tools.c'; then $(CYGPATH_W) 'kevin_tools.c'; else $(CYGPATH_W) '$(srcdir)/kevin_tools.c'; fi`
	mv -f $(DEPDIR)/gmodebug-in_development.Tpo $(DEPDIR)/gmodebug-in_development.Po
#	source='in_development.c' object='gmodebug-in_development.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gmodebug_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o gmodebug-in_development.obj `if test -f 'in_development.c'; then $(CYGPATH_W) 'kevin_tools.c'; else $(CYGPATH_W) '$(srcdir)/kevin_tools.c'; fi`

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	if test -z "$(ETAGS_ARGS)$$tags$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	    $$tags $$unique; \
	fi
ctags: CTAGS
CTAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(CTAGS_ARGS)$$tags$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$tags $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && cd $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) $$here

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d $(distdir) || mkdir $(distdir)
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -pR $(srcdir)/$$file $(distdir)$$dir || exit 1; \
	    fi; \
	    cp -pR $$d/$$file $(distdir)$$dir || exit 1; \
	  else \
	    test -f $(distdir)/$$file \
	    || cp -p $$d/$$file $(distdir)/$$file \
	    || exit 1; \
	  fi; \
	done
	-find $(distdir) -type d ! -perm -777 -exec chmod a+rwx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r $(distdir)
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | bzip2 -9 -c >$(distdir).tar.bz2
	$(am__remove_distdir)

dist-tarZ: distdir
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__remove_distdir)

dist-shar: distdir
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__remove_distdir)

dist dist-all: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gunzip -c $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bunzip2 -c $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gunzip -c $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir); chmod a+w $(distdir)
	mkdir $(distdir)/_build
	mkdir $(distdir)/_inst
	chmod a-w $(distdir)
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && cd $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck
	$(am__remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@cd $(distuninstallcheck_dir) \
	&& test `$(distuninstallcheck_listfiles) | wc -l` -le 1 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-am: Makefile $(PROGRAMS)
installdirs:
	for dir in "$(DESTDIR)$(bindir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

info: info-am

info-am:

install-data-am:

install-dvi: install-dvi-am

install-exec-am: install-binPROGRAMS

install-html: install-html-am

install-info: install-info-am

install-man:

install-pdf: install-pdf-am

install-ps: install-ps-am

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS

.MAKE: install-am install-strip

.PHONY: CTAGS GTAGS all all-am am--refresh check check-am clean \
	clean-binPROGRAMS clean-generic ctags dist dist-all dist-bzip2 \
	dist-gzip dist-shar dist-tarZ dist-zip distcheck distclean \
	distclean-compile distclean-generic distclean-tags \
	distcleancheck distdir distuninstallcheck dvi dvi-am html \
	html-am info info-am install install-am install-binPROGRAMS \
	install-data install-data-am install-dvi install-dvi-am \
	install-exec install-exec-am install-html install-html-am \
	install-info install-info-am install-man install-pdf \
	install-pdf-am install-ps install-ps-am install-strip \
	installcheck installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic pdf pdf-am ps ps-am tags uninstall \
	uninstall-am uninstall-binPROGRAMS

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
